name: MLB Betting RL System Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run deployment tests
      run: |
        python deploy_test.py
    
    - name: Run system tests
      run: |
        python test_system.py
    
    - name: Check code style
      run: |
        pip install flake8
        flake8 src/ --max-line-length=100 --ignore=E501,W503
    
    - name: Test data pipeline
      run: |
        python -c "from src.data.real_data_sources import RealDataSources; print('✅ Data pipeline test passed')"
    
    - name: Test simulation
      run: |
        python -c "from src.simulation.game_simulator import MonteCarloSimulator; print('✅ Simulation test passed')"
    
    - name: Test Kelly betting
      run: |
        python -c "from src.betting.kelly_betting import KellyBettingSystem; print('✅ Kelly betting test passed')" 